# Generated by Django 2.1 on 2018-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180820_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('result', models.IntegerField()),
                ('log_date', models.DateTimeField()),
            ],
        ),
    ]
